---
- hosts: localhost
  tasks:
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
    become: yes
    become_method: sudo
    become_user: root

  - name: Installing VSCode GPG Key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    become: yes
    become_method: sudo
    become_user: root

  - name: Installing VSCode Repo
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present
      filename: vscode
      update_cache: yes
    become: yes
    become_method: sudo
    become_user: root

  - name: Istalling VSCode
    apt:
      name: code
    become: yes
    become_method: sudo
    become_user: root
