- name: Importing Keys.
  rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  become: yes
  become_method: sudo
  become_user: root

# Since there is no dnf config-manager module yet, doing this manually.
- name: Adding Sublime Repo
  yum_repository:
    name: sublime-text
    description: Sublime Text - x86_64 - Stable
    file: sublime-text
    gpgcheck: yes
    enabled: yes
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  become: yes
  become_method: sudo
  become_user: root

- name: Install Desktop Packages
  dnf:
    name: "{{ item.name }}"
    state: installed 
  with_items:
    - { name: sublime-text }
    - { name: sublime-merge }
    - { name: guake }
    - { name: keepassx }
    - { name: parcellite }
    - { name: autokey-qt }
  become: yes
  become_method: sudo
  become_user: root

- name: Installing IDE Dependencies
  dnf:
    name: "{{ item.name }}"
    state: installed
  with_items:
    - { name: python2 }
    - { name: python3 }
    - { name: libXScrnSaver } # For Postman 
    - { name: java-latest-openjdk }
  become: yes
  become_method: sudo
  become_user: root

- name: Create a directory if it does not exist
  file:
    path: "{{ lookup('env','HOME') }}{{ item.path }}"
    state: directory
    mode: '0755'
  with_items:
    - { path: "/opt/" }
    - { path: "/bin/"}

- name: Downloading Instalers
  get_url: 
    url: "{{ item.url }}"
    dest: "{{ lookup('env','HOME') }}/opt/"
    checksum: "{{ item.checksum }}"
  with_items:
    - { url: "https://dl.pstmn.io/download/version/7.0.9/linux64", checksum: "sha1:6A2EC4886F7B94C5AE2780EF49276F840596F755"}
    - { url: "https://download.jetbrains.com/python/pycharm-professional-2019.1.1.tar.gz", checksum: "sha256:68a05bb3f037caf5944d17d03aeabd2be34a07eedb164d77f0617d22cf919141"}
    - { url: "https://download.jetbrains.com/webide/PhpStorm-2019.1.1.tar.gz", checksum: "sha256:39500e7f605662b8d59af29c94f295cf978dc7e8b3ea060ec27106c9b9821c80" }

- name: UnZipping Postman
  unarchive:
    src: "/opt/Postman-linux-x64-7.0.9.tar.gz"
    dest: "{{ lookup('env','HOME') }}/opt/"
  args: 
    creates: "{{ lookup('env','HOME') }}/opt/Postman"

- name: UnZipping PyCharm
  unarchive:
    src: "{{ lookup('env','HOME') }}/opt/pycharm-professional-2019.1.1.tar.gz"
    dest: "{{ lookup('env','HOME') }}/opt/"
  args:
    creates: "{{ lookup('env','HOME') }}/opt/pycharm-2019.1.1"

- name: UnZipping PHPStorm
  unarchive:
    src: "{{ lookup('env','HOME') }}/opt/PhpStorm-2019.1.1.tar.gz"
    dest: "{{ lookup('env','HOME') }}/opt/"
  args: 
    creates: "{{ lookup('env','HOME') }}/opt/PhpStorm-191.6707.66"

- name: Creating SymLink
  file: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    state: link
  with_items:
    - {src: "{{ lookup('env','HOME') }}/opt/Postman/app/Postman", dest: "{{ lookup('env','HOME') }}/bin/postman"}
    - {src: "{{ lookup('env','HOME') }}/opt/pycharm-2019.1.1/bin/pycharm.sh", dest: "{{ lookup('env','HOME') }}/bin/charm"}
    - {src: "{{ lookup('env','HOME') }}/opt/PhpStorm-191.6707.66/bin/phpstorm.sh", dest: "{{ lookup('env','HOME') }}/bin/storm"}

- name: Setting up Shortcuts
  vars:
    HOME: "{{ lookup('env','HOME') }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: templates/postman.desktop.j2, dest: "{{ lookup('env','HOME') }}/.local/share/applications/postman.desktop" }
    - { src: templates/phpstorm.desktop.j2, dest: "{{ lookup('env','HOME') }}/.local/share/applications/phpstorm.desktop" }
    - { src: templates/pycharm.desktop.j2, dest: "{{ lookup('env','HOME') }}/.local/share/applications/pycharm.desktop" }