- name: Importing Keys.
  rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

# Since there is no dnf config-manager module yet, doing this manually.
- name: Adding Sublime Repo
  yum_repository:
    name: sublime-text
    description: Sublime Text - x86_64 - Stable
    file: sublime-text
    gpgcheck: yes
    enabled: yes
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- name: Install Desktop Packages
  dnf:
    name: "{{ packages }}"
    state: installed 
  vars:
    packages:
    - sublime-text # Text Editor
    - sublime-merge # Git Client.
    - guake # Drop down terminal.
    - keepassx # KeePass client
    - parcellite # Clipboard manager
    - autokey-qt # AutoKey system.

- name: Installing IDE Dependencies
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
    - python2
    - python3
    - java-latest-openjdk

- name: Downloading JetBrain IDE's
  get_url: 
    url: "{{ item.url }}"
    dest: /opt/
    checksum: "{{ item.checksum }}"
  with_items:
    - { url: "https://download.jetbrains.com/python/pycharm-professional-2019.1.1.tar.gz", checksum: "sha256:68a05bb3f037caf5944d17d03aeabd2be34a07eedb164d77f0617d22cf919141"}
    - { url: "https://download.jetbrains.com/webide/PhpStorm-2019.1.1.tar.gz", checksum: "sha256:39500e7f605662b8d59af29c94f295cf978dc7e8b3ea060ec27106c9b9821c80" }

- name: UnZipping Archives
  unarchive:
    src: "{{ item.src }}"
    dest: /opt/
  with_items:
    - {src: /opt/pycharm-professional-2019.1.1.tar.gz}
    - {src: /opt/PhpStorm-2019.1.1.tar.gz}
  args: 
    creates: /opt/pycharm-2019.1.1
    creates: /opt/PhpStorm-191.6707.66

- name: Creating SymLink
  file: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
    state: link
  with_items:
    - {src: /opt/pycharm-2019.1.1/bin/pycharm.sh, dest: /usr/local/bin/charm}
    - {src: /opt/PhpStorm-191.6707.66/bin/phpstorm.sh, dest: /usr/local/bin/storm}

- name: Setting up Shortcuts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: files/phpstorm.desktop, dest: /usr/share/applications/phpstorm.desktop }
    - { src: files/pycharm.desktop, dest: /usr/share/applications/pycharm.desktop }