- name: Installing VSCode GPG Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Installing VSCode Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
    update_cache: yes

- name: Istalling VSCode
  apt:
    name: code