- name: Install Basic Packages
  dnf:
    name: "{{ item.name }}"
    state: installed 
  with_items:
    - { name: gcc }
    - { name: gdb }
    - { name: vim }
    - { name: screen }
    - { name: python3 }
